; PlatformIO Project Configuration File
;
; Standalone instrument pitch / note reader (Arduino + microphone FFT)

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
	kosme/arduinoFFT@^2.0.4
